POST http://localhost:8000/api/register/
Content-Type: application/json

{
    "username": "user14",
    "password": "123",
    "first_name": "first_name",
    "last_name": "last_name",
    "email": "12@q.com",
    "is_staff":"true",
    "storage_path":"123123123"
}

###

POST http://localhost:8000/api/token/login/
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}

###

POST http://localhost:8000/api/token/logout/
Authorization: Token 68c3cd7be5195b02ff8ac210c2826f81a52bf41f



###

GET http://localhost:8000/api/files/

###
POST http://localhost:8000/api/files/
Authorization: Token 75acb065e72e2a86a4f9a9854c08c8d609392946
Content-Type: application/json

{
  "name": "4564",
  "size": "1",
  "comment":"red.",
  "path": "This fie.",
  "url": "Th."
}

###

PATCH  http://localhost:8000/api/files/44/
Authorization: Token 89790a9890611366ee048605e5b8110e97818a1c
Content-Type: application/json

{
  "comment":"comment from 6"
}

###

DELETE http://localhost:8000/api/files/37/
Authorization: Token 69ef9510931928aa89a1f9d211ee1fa27a299a6c


###

GET  http://localhost:8000/api/users/9/
Authorization: Token da6814369447a21253b1cebf1b34d19696ea6ccc

###

DELETE  http://localhost:8000/api/users/10/
Authorization: Token f4feb0199ead88d9ff70b11278dae024d3032afe


###
PATCH http://localhost:8000/api/users/6/
Authorization: Token f4feb0199ead88d9ff70b11278dae024d3032afe
Content-Type: application/json

{
  "is_staff":"false"
}

### 
PATCH  http://localhost:8000/api/files/44/
Authorization: Token bbf0548020c3342f3e970b1e7a78cd2b55114b49
Content-Type: application/json

{
  "comment": "new_comment"
}


###
PATCH    http://localhost:8000/api/users/2/
Authorization: Token 1dcbb3e5ef45b373e2c5696f518ed571482fac54
Content-Type: application/json

{
  "first_name": "new_first_name"
}

###
GET  http://localhost:8000/api/auth/
Content-Type: application/json

{
  "key":"da6814369447a21253b1cebf1b34d19696ea6ccc"

}