POST http://localhost:8000/api/register/
Content-Type: application/json

{
    "username": "user2",
    "password": "123",
    "first_name": "user2",
    "last_name": "user2",
    "is_staff": "true",
    "email": "2@q.com",
    "storage_path":"77887788778789879879"
}

###

# POST http://localhost:8000/api/token/login/
# Content-Type: application/json

# {
#     "username": "456",
#     "password": "123"
# }

# ###

# POST http://localhost:8000/api/token/logout/
# Authorization: Token 68c3cd7be5195b02ff8ac210c2826f81a52bf41f

###

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "user10",
    "password": "Home752/"
}

###
POST http://localhost:8000/api/auth/logout/
Authorization: Token 18fc2e217c6124779fe984fac03a2e904f70d9c4




###

GET http://localhost:8000/api/files/53
Authorization: Token a348abcfcc1449282b19b6722f8f060aa60e33c3

###
POST http://localhost:8000/api/files/
Authorization: Token 75acb065e72e2a86a4f9a9854c08c8d609392946
Content-Type: application/json

{
  "name": "4564",
  "size": "1",
  "comment":"red.",
  "path": "This fie.",
  "url": "Th."
}

###

PATCH  http://localhost:8000/api/files/6/
Authorization: Token da213d9225bf718cbb266cca26dd8c9a28f7b1c4
Content-Type: application/json

{
  "comment":"comment from 9"
}

###

DELETE http://localhost:8000/api/files/37/
Authorization: Token 69ef9510931928aa89a1f9d211ee1fa27a299a6c


###

GET  http://localhost:8000/api/users/
Authorization: Token da213d9225bf718cbb266cca26dd8c9a28f7b1c4


###

DELETE  http://localhost:8000/api/users/1/
Authorization: Token 259c1c65291d50a6f06cf8337b9e59fe630ae31c


###
PATCH http://localhost:8000/api/users/6/
Authorization: Token f4feb0199ead88d9ff70b11278dae024d3032afe
Content-Type: application/json

{
  "is_staff":"false"
}

### 
PATCH  http://localhost:8000/api/files/44/
Authorization: Token bbf0548020c3342f3e970b1e7a78cd2b55114b49
Content-Type: application/json

{
  "comment": "new_comment"
}


###
PATCH    http://localhost:8000/api/users/2/
Authorization: Token 1dcbb3e5ef45b373e2c5696f518ed571482fac54
Content-Type: application/json

{
  "first_name": "new_first_name"
}

###
GET  http://localhost:8000/api/auth/
Content-Type: application/json

{
  "key":"da6814369447a21253b1cebf1b34d19696ea6ccc"

}

###

GET http://localhost:8000/api/download/51

###
GET http://localhost:8000/api/files/?owner=6&&ordering=name
Authorization: Token 4754cc09dfc9a5b7013e997c40e4d805cd5efd1c



###

POST http://localhost:8000/api/sauth/login/
Content-Type: application/json

{
    "username": "admin1",
    "password": "123"
}

###

POST http://localhost:8000/api/drf-auth/logout/
Authorization: Basic l2915q60vveky9xznd8kzkrz1p3isnlc


###

GET  http://localhost:8000/api/files/
Authorization: Basic x6qxe9wh9prqbshalt95ha8mn4u0cube
X-CSRFToken: DOqAa587yszzQDUBb0FZdjgJ0yVbErfQ