# Generated by Django 5.1.3 on 2024-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
