# Generated by Django 5.1.3 on 2024-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='downloaded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(max_length=10),
        ),
    ]
