# Generated by Django 5.1.3 on 2024-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
